In [21]:
import datetime
import matplotlib.pyplot as plt
import numpy as np
import os
import pandas as pd
import random
import sys
from datetime import timedelta  

if sys.version_info[0] < 3: 
    from StringIO import StringIO
else:
    from io import StringIO
    
from IPython.display import HTML
def View(df):
    css = """<style>
    table { border-collapse: collapse; border: 3px solid #eee; }
    table tr th:first-child { background-color: #eeeeee; color: #333; font-weight: bold }
    table thead th { background-color: #eee; color: #000; }
    tr, th, td { border: 1px solid #ccc; border-width: 1px 0 0 1px; border-collapse: collapse;
    padding: 3px; font-family: monospace; font-size: 10px }</style>
    """
    s  = '<script type="text/Javascript">'
    s += 'var win = window.open("", "Title", "toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=yes, resizable=yes, width=780, height=200, top="+(screen.height-400)+", left="+(screen.width-840));'
    s += 'win.document.body.innerHTML = \'' + (df.to_html() + css).replace("\n",'\\') + '\';'
    s += '</script>'
    return(HTML(s+css))    
    
print("Current Working directory " , os.getcwd())

Current Working directory  C:\Users\User\GitHub\WebET_Analysis

In [22]:
data_et = pd.read_csv(r'C:/Users/User/GitHub/WebET_Analysis/data_jupyter/data_et.csv')
data_et_fixation = pd.read_csv(r'C:/Users/User/GitHub/WebET_Analysis/data_jupyter/data_et_fixation.csv')
data_et_choice = pd.read_csv(r'C:/Users/User/GitHub/WebET_Analysis/data_jupyter/data_et_choice.csv')

data_trial = pd.read_csv(
    r'C:/Users/User/GitHub/WebET_Analysis/data_jupyter/data_trial.csv')
data_trial_fixation = pd.read_csv(
    r'C:/Users/User/GitHub/WebET_Analysis/data_jupyter/data_trial_fixation.csv')
data_trial_choice = pd.read_csv(
    r'C:/Users/User/GitHub/WebET_Analysis/data_jupyter/data_trial_choice.csv')

data_subject = pd.read_csv(r'C:/Users/User/GitHub/WebET_Analysis/data_jupyter/data_subject.csv') \
    .rename(columns=
            {
                'chosenAmount': 'bonus_pay',
                'chosenDelay': 'bonus_delay'
            }
           )    

overview = pd.DataFrame(
    [
        [len(data_et)],
        [len(data_et_fixation)],
        [len(data_et_choice)],
        [len(data_trial)],
        [len(data_trial_fixation)],
        [len(data_trial_choice)],
        [len(data_subject)]
    ], 
    columns=['length'],
    index=['data_et', 'data_et_fixation', 'data_et_choice', 
           'data_trial', 'data_trial_fixation', 'data_trial_choice', 
           'data_subject'])
print(overview)

C:\Users\User\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (40,56,57,58) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

                     length
data_et              520318
data_et_fixation     160870
data_et_choice       131254
data_trial            25576
data_trial_fixation    3499
data_trial_choice      3548
data_subject             51

# Approve subjects

In [3]:
path = 'data_cognition'
subject_files = os.listdir(path)
for i in range(0, len(subject_files)):
    thisSubject = open(path + "/" + subject_files[i]).read()
    if thisSubject.find('5edc20443467e28ec4e30f93') > (-1):
        print(subject_files[i])

In [4]:
if 'trial_length' in data_subject.columns: 
    print('trial_length already added!')
else:
    output = []
    for subject in data_trial['run_id'].unique():
        prolificID = data_trial.loc[data_trial['run_id']==subject, 'prolificID'].unique()[0]
        trial_length = len(data_trial.loc[data_trial['run_id']==subject, 'trial_index'].unique())
        output.append([subject, prolificID, trial_length])
    output = pd.DataFrame(output,
                 columns=['run_id', 'prolificID', 'trial_length']
                )

    data_subject = data_subject.merge(output, on=['run_id', 'prolificID'], how='left')

In [5]:
data_et = data_et.merge(
    data_trial.loc[:, ['run_id', 'chinFirst', 'trial_index', 'trial_type', 'task_nr']], 
    on=['run_id', 'trial_index'], 
    how='left'
)

In [6]:
output = []
for subject in data_et['run_id'].unique():
    m_x_fix = data_et.loc[
        (data_et['run_id']==subject) &
        (data_et['trial_type']=='eyetracking-fix-object') &
        ~((data_et['chinFirst']==1) & (data_et['task_nr']==2) |
          (data_et['chinFirst']==0) & (data_et['task_nr']==3) 
         ), 
        'x'
    ].mean()
    m_x_choice = data_et.loc[
        (data_et['run_id']==subject) &
        (data_et['trial_type']=='eyetracking-choice'), 
        'x'
    ].mean()

    m_y_fix = data_et.loc[
        (data_et['run_id']==subject) &
        (data_et['trial_type']=='eyetracking-fix-object') &
        ~((data_et['chinFirst']==1) & (data_et['task_nr']==2) |
          (data_et['chinFirst']==0) & (data_et['task_nr']==3) 
         ), 
        'y'
    ].mean()
    m_y_choice = data_et.loc[
        (data_et['run_id']==subject) &
        (data_et['trial_type']=='eyetracking-choice'), 
        'y'
    ].mean()

    m_count_fix = data_et.loc[
        (data_et['run_id']==subject) &
        (data_et['trial_type']=='eyetracking-fix-object') &
        ~((data_et['chinFirst']==1) & (data_et['task_nr']==2) |
          (data_et['chinFirst']==0) & (data_et['task_nr']==3) 
         ), 
        'x'
    ].count()

    m_count_choice = data_et.loc[
        (data_et['run_id']==subject) &
        (data_et['trial_type']=='eyetracking-choice'), 
        'x'
    ].count()
    
    m_choseTop = data_trial_choice.loc[data_trial_choice['run_id']==subject,
                                       'choseTop'].mean()

    output.append([subject, m_x_fix, m_y_fix, m_x_choice, m_y_choice, 
                   m_count_fix, m_count_choice, 
                   m_choseTop])

output = pd.DataFrame(output, 
                      columns=['run_id', 'm_x_fix', 'm_y_fix', 'm_x_choice', 'm_y_choice', 
                               'm_count_fix', 'm_count_choice',
                               'm_choseTop'])
output

data_subject = data_subject.merge(output, on='run_id', how='left')

## These subjects await review

In [7]:
data_subject.loc[data_subject['status']=='AWAITING REVIEW', 
                 ['run_id', 'prolificID', 'trial_length',
                 'm_x_fix', 'm_y_fix', 'm_x_choice', 'm_y_choice', 'm_count_fix', 'm_count_choice',
                 'm_choseTop']
                ].sort_values(by='prolificID')

Empty DataFrame
Columns: [run_id, prolificID, trial_length, m_x_fix, m_y_fix, m_x_choice, m_y_choice, m_count_fix, m_count_choice, m_choseTop]
Index: []

In [8]:
data_subject.columns

Index(['chinFirst', 'choiceTask_amountLeftFirst', 'bonus_pay', 'bonus_delay',
       'run_id', 'prolificID', 'age', 'browliner', 'browser',
       'browser_version', 'degree', 'device', 'ethnic', 'eyeliner',
       'eyeshadow', 'gender', 'glasses', 'keptHead', 'masquara',
       'optionalNote', 'platform', 'platform_version', 'sight', 'triedChin',
       'user_agent', 'vertPosition', 'webcam_fps', 'webcam_height',
       'webcam_label', 'webcam_width', 'session_id', 'status',
       'started_datetime', 'completed_date_time', 'time_taken', 'age_2',
       'num_approvals', 'num_rejections', 'prolific_score',
       'reviewed_at_datetime', 'entered_code', 'Country of Birth',
       'Current Country of Residence', 'Employment Status', 'First Language',
       'Nationality', 'Sex', 'Student Status', 'date', 'trial_length',
       'm_x_fix', 'm_y_fix', 'm_x_choice', 'm_y_choice', 'm_count_fix',
       'm_count_choice', 'm_choseTop'],
      dtype='object')

In [9]:
if 'choice_rt' in data_subject.columns:
    print('choice_rt already added!')
else: 
    grouped = data_trial.loc[data_trial['trial_type']=='eyetracking-choice', :] \
        .groupby(['prolificID'])['trial_duration_exact'].mean() \
        .reset_index() \
        .rename(columns={'trial_duration_exact': 'choice_rt'})
    data_subject = data_subject.merge(grouped, on='prolificID', how='left')

data_subject.loc[
    data_subject['status']=='AWAITING REVIEW', 
    ['run_id', 'prolificID', 'webcam_fps', 'choice_rt', 'bonus_pay', 'bonus_delay']
] \
    .sort_values(by='run_id')

Empty DataFrame
Columns: [run_id, prolificID, webcam_fps, choice_rt, bonus_pay, bonus_delay]
Index: []

# Basic payment

In [10]:
data_pay = data_subject.loc[data_subject['status']=='APPROVED', 
                            [
                                'run_id', 'prolificID', 
                                'age',  'Country of Birth', 'Current Country of Residence', 'First Language',
                                'Nationality', 'Sex',
                                'status', 'reviewed_at_datetime', 'Country of Birth', 'entered_code',
                                'session_id', 'started_datetime', 'completed_date_time', 'time_taken',
                                'bonus_pay', 'bonus_delay'
                            ]
                           ]

data_pay['basic_pay'] = 2.25

# Bonus payment

In [11]:
data_pay[['run_id', 'prolificID', 'bonus_pay']]

    run_id                prolificID  bonus_pay
1      103  600063f2943eab0acc812ed8        4.5
2       11  5c5684ef9d244c0001b29f1e        3.5
3       12  5b8969006651ea000118e42e        NaN
5      126  5c0e4e3d87e876000151cfec        4.5
6      128  5f01a0893963d02ea1d65d12        4.5
7       13  5b4e65de09f5af0001080f45        5.0
8      130  5fea19869bf07d97b4a87ae8        4.0
9      131  5e53a7b4d9a7ea3a2b062da0        3.5
10      19  5f860a189bc695131f22ec9c        4.5
11      24  5f77a902fc647a327b77004a        3.0
12      25  5cf0ccf488abf10019fb775d        4.5
13      28  5f561a95aa1c4ea13672f138        2.5
14      30  5eeaa0ffaa6af11cf32ce057        3.0
15      32  5ea94df3a879f002f3e9a812        4.5
16      36  5f8472685956c40c720d0936        0.5
17      37  5f0cb319d29147695796a208        3.0
18      38  5f1e9db721e4f101783fe21c        4.0
19       4  5f96fc2552ce3f040af63bbc        4.5
20      41  5f881c7d29650a26096e77a3        4.5
21      42  5fcbb3066829ff1a601fe080        5.0
22      43  5f946436ae32a127565d9405        4.0
23      45  5f1aac6058391f01dacbf619        4.5
24      47  5f5793d85411a8251740e602        4.5
25      48  5fa1192cf99e161a5cfad1cd        4.0
26       5  5ea3f75481a44e39aa318256        4.5
27      56  5e79d99f6873570009367716        4.5
28      58  5de5157820c5aa09b7a53b89        5.0
29      59  5fe6fb05b9b609059e4613e0        4.0
30       6  5f4e08aafb74230a29cb4ef0        5.0
31      61  5fb2af792942a58ffe303948        NaN
32      63  5fc6bcbc6da34d0f8dd78a3a        4.0
33      66  5bd170999afb5b00015ba3b1        5.0
34      67  5cfb9f6f288ca80001169952        2.0
35       7  5fd41bf508717e1833d8aed7        4.0
36      70  5d430fdf871f1700017b2a81        5.0
37      74  5aa7b522b5e2110001c74775        5.0
38      75  5d00bb3b51669b000136a986        5.0
39      80  5fa69c24315bfb2d0a37c685        4.0
40      81  5c6cb4163023800001e71898        3.5
41      85  5e2db0f07dc16b3a611516bd        4.5
42       9  5fea6632bf9ae4a79153efdf        NaN
43      90  5cf67b30c5cf0e00010c00fc        3.0
44      91  5f256074297aac1d8ef7382d        2.5
45      92  5f91b067130f8504520cdd6f        4.5
46      93  5f4756db83588013e9e31bfc        2.0
47      94  5ecfc227f036c902457fc44c        4.0
48      96  5eb9940830ab6c098bd1943d        4.5
49      97  5f68fe5be5cc370c0a0911de        4.5
50      98  5f779405dacc842fc44bc767        4.0

## Replace empty values with the best bonus reward

In [12]:
# For two subjects, the bonus payment was not recorded
data_pay.loc[
    data_pay['prolificID'].isin(
        ['5fea6632bf9ae4a79153efdf', 
         '5b8969006651ea000118e42e', 
         '5fb2af792942a58ffe303948', 
        ]
    ), ['bonus_pay', 'bonus_delay']] = [5, 1]

data_pay.loc[data_pay[['bonus_pay', 'bonus_delay']].isnull().any(axis=1), :]

Empty DataFrame
Columns: [run_id, prolificID, age, Country of Birth, Current Country of Residence, First Language, Nationality, Sex, status, reviewed_at_datetime, Country of Birth, entered_code, session_id, started_datetime, completed_date_time, time_taken, bonus_pay, bonus_delay, basic_pay]
Index: []

## What bonus is due today?

In [13]:
data_pay['completed_date']=data_pay.apply(
    lambda x: datetime.datetime.strptime(
        x['completed_date_time'], '%Y-%m-%d %H:%M:%S.%f') \
            .date(),
    axis=1)
data_pay.bonus_pay

1     4.5
2     3.5
3     5.0
5     4.5
6     4.5
7     5.0
8     4.0
9     3.5
10    4.5
11    3.0
12    4.5
13    2.5
14    3.0
15    4.5
16    0.5
17    3.0
18    4.0
19    4.5
20    4.5
21    5.0
22    4.0
23    4.5
24    4.5
25    4.0
26    4.5
27    4.5
28    5.0
29    4.0
30    5.0
31    5.0
32    4.0
33    5.0
34    2.0
35    4.0
36    5.0
37    5.0
38    5.0
39    4.0
40    3.5
41    4.5
42    5.0
43    3.0
44    2.5
45    4.5
46    2.0
47    4.0
48    4.5
49    4.5
50    4.0
Name: bonus_pay, dtype: float64

In [14]:
data_pay['reward_pound'] = data_pay['bonus_pay'] * 0.75

In [15]:
data_pay['due_on'] = data_pay['completed_date'] +  data_pay['bonus_delay'].map(datetime.timedelta) 

data_pay.loc[:, 
               [
                   'prolificID', 'run_id',
                   'Nationality', 'Sex',  
                   'completed_date', 'bonus_pay', 'bonus_delay', 
                   'reward_pound', 'due_on'
               ]
              ]. sort_values(by='due_on')

C:\Users\User\Anaconda3\lib\site-packages\pandas\core\arrays\datetimelike.py:1268: PerformanceWarning: Adding/subtracting array of DateOffsets to TimedeltaArray not vectorized
  PerformanceWarning,

,prolificID,run_id,Nationality,Sex,completed_date,bonus_pay,bonus_delay,reward_pound,due_on
2,5c5684ef9d244c0001b29f1e,11,United States,Male,2021-01-18,3.5,0.0,2.625,2021-01-18
11,5f77a902fc647a327b77004a,24,United Kingdom,Female,2021-01-18,3.0,0.0,2.250,2021-01-18
17,5f0cb319d29147695796a208,37,Italy,Male,2021-01-18,3.0,0.0,2.250,2021-01-18
13,5f561a95aa1c4ea13672f138,28,Italy,Male,2021-01-18,2.5,0.0,1.875,2021-01-18
14,5eeaa0ffaa6af11cf32ce057,30,Poland,Male,2021-01-18,3.0,0.0,2.250,2021-01-18
16,5f8472685956c40c720d0936,36,Italy,Male,2021-01-18,0.5,0.0,0.375,2021-01-18
18,5f1e9db721e4f101783fe21c,38,Poland,Male,2021-01-18,4.0,1.0,3.000,2021-01-19
27,5e79d99f6873570009367716,56,United Kingdom,Female,2021-01-19,4.5,0.0,3.375,2021-01-19
43,5cf67b30c5cf0e00010c00fc,90,Spain,Female,2021-01-19,3.0,0.0,2.250,2021-01-19
24,5f5793d85411a8251740e602,47,Poland,Male,2021-01-19,4.5,0.0,3.375,2021-01-19
44,5f256074297aac1d8ef7382d,91,Hungary,Male,2021-01-19,2.5,0.0,1.875,2021-01-19
21,5fcbb3066829ff1a601fe080,42,United Kingdom,Female,2021-01-18,5.0,1.0,3.750,2021-01-19
40,5c6cb4163023800001e71898,81,Greece,Male,2021-01-19,3.5,0.0,2.625,2021-01-19
42,5fea6632bf9ae4a79153efdf,9,Serbia,Male,2021-01-18,5.0,1.0,3.750,2021-01-19
34,5cfb9f6f288ca80001169952,67,Poland,Male,2021-01-19,2.0,0.0,1.500,2021-01-19
46,5f4756db83588013e9e31bfc,93,South Africa,Male,2021-01-19,2.0,0.0,1.500,2021-01-19
9,5e53a7b4d9a7ea3a2b062da0,131,United Kingdom,Female,2021-01-19,3.5,0.0,2.625,2021-01-19
8,5fea19869bf07d97b4a87ae8,130,Spain,Male,2021-01-19,4.0,0.0,3.000,2021-01-19
3,5b8969006651ea000118e42e,12,Italy,Female,2021-01-18,5.0,1.0,3.750,2021-01-19
31,5fb2af792942a58ffe303948,61,Germany,Female,2021-01-19,5.0,1.0,3.750,2021-01-20
41,5e2db0f07dc16b3a611516bd,85,United Kingdom,Female,2021-01-19,4.5,1.0,3.375,2021-01-20
10,5f860a189bc695131f22ec9c,19,Poland,Male,2021-01-18,4.5,7.0,3.375,2021-01-25
25,5fa1192cf99e161a5cfad1cd,48,Poland,Male,2021-01-19,4.0,7.0,3.000,2021-01-26
36,5d430fdf871f1700017b2a81,70,Spain,Male,2021-01-19,5.0,7.0,3.750,2021-01-26
6,5f01a0893963d02ea1d65d12,128,Greece,Male,2021-01-19,4.5,7.0,3.375,2021-01-26
39,5fa69c24315bfb2d0a37c685,80,Poland,Male,2021-01-19,4.0,7.0,3.000,2021-01-26
30,5f4e08aafb74230a29cb4ef0,6,Poland,Male,2021-01-18,5.0,15.0,3.750,2021-02-02
45,5f91b067130f8504520cdd6f,92,Italy,Male,2021-01-19,4.5,15.0,3.375,2021-02-03
47,5ecfc227f036c902457fc44c,94,United Kingdom,Female,2021-01-19,4.0,15.0,3.000,2021-02-03
28,5de5157820c5aa09b7a53b89,58,Greece,Male,2021-01-19,5.0,15.0,3.750,2021-02-03
29,5fe6fb05b9b609059e4613e0,59,Mexico,Male,2021-01-19,4.0,15.0,3.000,2021-02-03
32,5fc6bcbc6da34d0f8dd78a3a,63,Poland,Male,2021-01-19,4.0,15.0,3.000,2021-02-03
35,5fd41bf508717e1833d8aed7,7,Mexico,Male,2021-01-18,4.0,30.0,3.000,2021-02-17
26,5ea3f75481a44e39aa318256,5,Israel,Male,2021-01-18,4.5,30.0,3.375,2021-02-17
19,5f96fc2552ce3f040af63bbc,4,Spain,Male,2021-01-18,4.5,30.0,3.375,2021-02-17
7,5b4e65de09f5af0001080f45,13,Poland,Male,2021-01-18,5.0,30.0,3.750,2021-02-17
22,5f946436ae32a127565d9405,43,Portugal,Male,2021-01-18,4.0,30.0,3.000,2021-02-17
20,5f881c7d29650a26096e77a3,41,United Kingdom,Male,2021-01-18,4.5,30.0,3.375,2021-02-17
50,5f779405dacc842fc44bc767,98,Portugal,Male,2021-01-19,4.0,30.0,3.000,2021-02-18
37,5aa7b522b5e2110001c74775,74,United Kingdom,Female,2021-01-19,5.0,30.0,3.750,2021-02-18
33,5bd170999afb5b00015ba3b1,66,Portugal,Female,2021-01-19,5.0,30.0,3.750,2021-02-18
49,5f68fe5be5cc370c0a0911de,97,United Kingdom,Female,2021-01-19,4.5,30.0,3.375,2021-02-18
23,5f1aac6058391f01dacbf619,45,Poland,Male,2021-01-19,4.5,30.0,3.375,2021-02-18
38,5d00bb3b51669b000136a986,75,Poland,Male,2021-01-19,5.0,30.0,3.750,2021-02-18
15,5ea94df3a879f002f3e9a812,32,Poland,Female,2021-01-18,4.5,90.0,3.375,2021-04-18
12,5cf0ccf488abf10019fb775d,25,United Kingdom,Female,2021-01-18,4.5,90.0,3.375,2021-04-18
5,5c0e4e3d87e876000151cfec,126,Poland,Female,2021-01-19,4.5,90.0,3.375,2021-04-19
48,5eb9940830ab6c098bd1943d,96,Israel,Male,2021-01-19,4.5,90.0,3.375,2021-04-19
1,600063f2943eab0acc812ed8,103,Italy,Male,2021-01-19,4.5,180.0,3.375,2021-07-18

In [20]:
bonus_due_today = data_pay.loc[data_pay['due_on']==datetime.datetime.now().date(), :]
bonus_due_today['reward_pound'] = bonus_due_today['reward_pound'].round(2)
bonus_due_today

C:\Users\User\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,run_id,prolificID,age,Country of Birth,Current Country of Residence,First Language,Nationality,Sex,status,reviewed_at_datetime,...,completed_date_time,time_taken,bonus_pay,bonus_delay,basic_pay,completed_date,reward_pound,due_on,basic_cost,total_cost
31,61,5fb2af792942a58ffe303948,NaN,Germany,Germany,NaN,Germany,Female,APPROVED,2021-01-19 10:27:47.454000,...,2021-01-19 09:37:01.137000,1648.576,5.0,1.0,2.25,2021-01-19,3.75,2021-01-20,3.15,10.15
41,85,5e2db0f07dc16b3a611516bd,1982.0,United Kingdom,United Kingdom,English,United Kingdom,Female,APPROVED,2021-01-19 11:00:04.816000,...,2021-01-19 09:32:30.113000,1199.651,4.5,1.0,2.25,2021-01-19,3.38,2021-01-20,3.15,9.45

In [17]:
bonus_due_today.loc[: , ['prolificID', 'reward_pound']] \
    .to_csv('C:/Users/User/Google Drive/Masterarbeit/Acquise/bonusToday.csv', 
            index=False, 
            header=False
           )
print(bonus_due_today['due_on'].unique())

[datetime.date(2021, 1, 20)]

# Total costs

In [18]:
data_pay['basic_cost'] = data_pay['basic_pay'] * 1.4
data_pay['total_cost'] = (data_pay['basic_pay'] + data_pay['bonus_pay']) * 1.4
print('Basic Costs: ' + str(sum(data_pay['basic_cost'])))
print('Total Costs: ' + str(sum(data_pay['total_cost'])))
data_pay

Basic Costs: 154.35000000000014
Total Costs: 432.9499999999997

,run_id,prolificID,age,Country of Birth,Current Country of Residence,First Language,Nationality,Sex,status,reviewed_at_datetime,...,completed_date_time,time_taken,bonus_pay,bonus_delay,basic_pay,completed_date,reward_pound,due_on,basic_cost,total_cost
1,103,600063f2943eab0acc812ed8,2001.0,Italy,Italy,NaN,Italy,Male,APPROVED,2021-01-19 10:58:01.081000,...,2021-01-19 09:52:42.663000,1760.968,4.5,180.0,2.25,2021-01-19,3.375,2021-07-18,3.15,9.45
2,11,5c5684ef9d244c0001b29f1e,1991.0,Hong Kong,United States,Chinese,United States,Male,APPROVED,2021-01-18 10:53:28.738000,...,2021-01-18 08:53:34.578000,1227.532,3.5,0.0,2.25,2021-01-18,2.625,2021-01-18,3.15,8.05
3,12,5b8969006651ea000118e42e,1999.0,Italy,Italy,Italian,Italy,Female,APPROVED,2021-01-18 10:42:25.881000,...,2021-01-18 08:56:36.517000,1403.632,5.0,1.0,2.25,2021-01-18,3.750,2021-01-19,3.15,10.15
5,126,5c0e4e3d87e876000151cfec,1991.0,Poland,Poland,Polish,Poland,Female,APPROVED,2021-01-19 12:36:10.712000,...,2021-01-19 10:48:08.094000,1912.745,4.5,90.0,2.25,2021-01-19,3.375,2021-04-19,3.15,9.45
6,128,5f01a0893963d02ea1d65d12,1994.0,Germany,Greece,Greek,Greece,Male,APPROVED,2021-01-19 12:36:47.163000,...,2021-01-19 11:01:30.874000,2288.987,4.5,7.0,2.25,2021-01-19,3.375,2021-01-26,3.15,9.45
7,13,5b4e65de09f5af0001080f45,2001.0,Poland,Poland,Polish,Poland,Male,APPROVED,2021-01-18 10:56:07.011000,...,2021-01-18 08:57:22.141000,1692.194,5.0,30.0,2.25,2021-01-18,3.750,2021-02-17,3.15,10.15
8,130,5fea19869bf07d97b4a87ae8,2001.0,Spain,Spain,NaN,Spain,Male,APPROVED,2021-01-19 13:24:23.588000,...,2021-01-19 13:01:50.367000,1349.099,4.0,0.0,2.25,2021-01-19,3.000,2021-01-19,3.15,8.75
9,131,5e53a7b4d9a7ea3a2b062da0,NaN,United Kingdom,United Kingdom,English,United Kingdom,Female,APPROVED,2021-01-19 13:24:22.246000,...,2021-01-19 13:02:58.242000,1415.591,3.5,0.0,2.25,2021-01-19,2.625,2021-01-19,3.15,8.05
10,19,5f860a189bc695131f22ec9c,2000.0,Poland,Poland,DATA EXPIRED,Poland,Male,APPROVED,2021-01-18 10:57:59.489000,...,2021-01-18 09:02:09.783000,2116.522,4.5,7.0,2.25,2021-01-18,3.375,2021-01-25,3.15,9.45
11,24,5f77a902fc647a327b77004a,1993.0,United Kingdom,United Kingdom,DATA EXPIRED,United Kingdom,Female,APPROVED,2021-01-18 17:54:59.440000,...,2021-01-18 11:35:07.643000,2115.673,3.0,0.0,2.25,2021-01-18,2.250,2021-01-18,3.15,7.35
12,25,5cf0ccf488abf10019fb775d,2001.0,New Zealand,United Kingdom,Twi,United Kingdom,Female,APPROVED,2021-01-18 17:55:09.667000,...,2021-01-18 11:31:47.394000,1913.891,4.5,90.0,2.25,2021-01-18,3.375,2021-04-18,3.15,9.45
13,28,5f561a95aa1c4ea13672f138,1983.0,Italy,United Kingdom,DATA EXPIRED,Italy,Male,APPROVED,2021-01-18 17:55:18.379000,...,2021-01-18 11:19:56.498000,1197.589,2.5,0.0,2.25,2021-01-18,1.875,2021-01-18,3.15,6.65
14,30,5eeaa0ffaa6af11cf32ce057,2000.0,Poland,Poland,Polish,Poland,Male,APPROVED,2021-01-18 17:55:26.984000,...,2021-01-18 11:22:28.884000,1351.104,3.0,0.0,2.25,2021-01-18,2.250,2021-01-18,3.15,7.35
15,32,5ea94df3a879f002f3e9a812,1997.0,Poland,Poland,Polish,Poland,Female,APPROVED,2021-01-18 17:55:32.282000,...,2021-01-18 12:13:24.296000,4402.360,4.5,90.0,2.25,2021-01-18,3.375,2021-04-18,3.15,9.45
16,36,5f8472685956c40c720d0936,1999.0,Italy,Italy,DATA EXPIRED,Italy,Male,APPROVED,2021-01-18 17:55:37.264000,...,2021-01-18 11:25:29.598000,1453.841,0.5,0.0,2.25,2021-01-18,0.375,2021-01-18,3.15,3.85
17,37,5f0cb319d29147695796a208,1984.0,Italy,United Kingdom,Italian,Italy,Male,APPROVED,2021-01-18 17:55:43.824000,...,2021-01-18 11:27:28.919000,1531.289,3.0,0.0,2.25,2021-01-18,2.250,2021-01-18,3.15,7.35
18,38,5f1e9db721e4f101783fe21c,2001.0,Poland,Poland,Polish,Poland,Male,APPROVED,2021-01-19 11:09:24.649000,...,2021-01-18 11:57:55.636000,3482.451,4.0,1.0,2.25,2021-01-18,3.000,2021-01-19,3.15,8.75
19,4,5f96fc2552ce3f040af63bbc,1997.0,Spain,Spain,DATA EXPIRED,Spain,Male,APPROVED,2021-01-18 10:57:45.132000,...,2021-01-18 08:59:18.484000,1886.868,4.5,30.0,2.25,2021-01-18,3.375,2021-02-17,3.15,9.45
20,41,5f881c7d29650a26096e77a3,1992.0,United Kingdom,United Kingdom,DATA EXPIRED,United Kingdom,Male,APPROVED,2021-01-18 17:55:48.738000,...,2021-01-18 11:26:26.947000,1310.641,4.5,30.0,2.25,2021-01-18,3.375,2021-02-17,3.15,9.45
21,42,5fcbb3066829ff1a601fe080,1986.0,United Kingdom,United Kingdom,DATA EXPIRED,United Kingdom,Female,APPROVED,2021-01-18 17:55:53.348000,...,2021-01-18 11:31:52.156000,1506.437,5.0,1.0,2.25,2021-01-18,3.750,2021-01-19,3.15,10.15
22,43,5f946436ae32a127565d9405,1996.0,Portugal,Portugal,NaN,Portugal,Male,APPROVED,2021-01-18 17:55:58.249000,...,2021-01-18 11:38:20.975000,1667.728,4.0,30.0,2.25,2021-01-18,3.000,2021-02-17,3.15,8.75
23,45,5f1aac6058391f01dacbf619,1988.0,Poland,Poland,Polish,Poland,Male,APPROVED,2021-01-19 11:00:16.312000,...,2021-01-19 09:36:01.081000,1609.939,4.5,30.0,2.25,2021-01-19,3.375,2021-02-18,3.15,9.45
24,47,5f5793d85411a8251740e602,2001.0,Poland,Poland,DATA EXPIRED,Poland,Male,APPROVED,2021-01-19 11:00:28.992000,...,2021-01-19 09:35:13.831000,1557.240,4.5,0.0,2.25,2021-01-19,3.375,2021-01-19,3.15,9.45
25,48,5fa1192cf99e161a5cfad1cd,2001.0,Poland,Poland,DATA EXPIRED,Poland,Male,APPROVED,2021-01-19 11:00:41.549000,...,2021-01-19 09:44:13.747000,2095.130,4.0,7.0,2.25,2021-01-19,3.000,2021-01-26,3.15,8.75
26,5,5ea3f75481a44e39aa318256,1994.0,Israel,Israel,Russian,Israel,Male,APPROVED,2021-01-18 10:57:35.455000,...,2021-01-18 08:53:41.102000,1536.061,4.5,30.0,2.25,2021-01-18,3.375,2021-02-17,3.15,9.45
27,56,5e79d99f6873570009367716,1994.0,United Kingdom,United Kingdom,English,United Kingdom,Female,APPROVED,2021-01-19 11:50:27.571000,...,2021-01-19 09:28:48.680000,1159.061,4.5,0.0,2.25,2021-01-19,3.375,2021-01-19,3.15,9.45
28,58,5de5157820c5aa09b7a53b89,1999.0,Greece,Greece,Greek,Greece,Male,APPROVED,2021-01-19 10:59:59.217000,...,2021-01-19 09:37:53.111000,1702.131,5.0,15.0,2.25,2021-01-19,3.750,2021-02-03,3.15,10.15
29,59,5fe6fb05b9b609059e4613e0,1997.0,Mexico,Mexico,DATA EXPIRED,Mexico,Male,APPROVED,2021-01-19 11:01:03.595000,...,2021-01-19 09:41:48.951000,1938.240,4.0,15.0,2.25,2021-01-19,3.000,2021-02-03,3.15,8.75
30,6,5f4e08aafb74230a29cb4ef0,2001.0,Poland,Poland,DATA EXPIRED,Poland,Male,APPROVED,2021-01-18 10:58:32.736000,...,2021-01-18 08:56:30.571000,1589.581,5.0,15.0,2.25,2021-01-18,3.750,2021-02-02,3.15,10.15
31,61,5fb2af792942a58ffe303948,NaN,Germany,Germany,NaN,Germany,Female,APPROVED,2021-01-19 10:27:47.454000,...,2021-01-19 09:37:01.137000,1648.576,5.0,1.0,2.25,2021-01-19,3.750,2021-01-20,3.15,10.15
32,63,5fc6bcbc6da34d0f8dd78a3a,2001.0,Poland,Poland,DATA EXPIRED,Poland,Male,APPROVED,2021-01-19 11:00:59.173000,...,2021-01-19 09:59:49.124000,3026.498,4.0,15.0,2.25,2021-01-19,3.000,2021-02-03,3.15,8.75
33,66,5bd170999afb5b00015ba3b1,1969.0,Portugal,Portugal,Portuguese,Portugal,Female,APPROVED,2021-01-19 10:59:31.598000,...,2021-01-19 09:41:41.480000,1921.967,5.0,30.0,2.25,2021-01-19,3.750,2021-02-18,3.15,10.15
34,67,5cfb9f6f288ca80001169952,1990.0,Poland,Poland,Polish,Poland,Male,APPROVED,2021-01-19 10:59:40.829000,...,2021-01-19 09:35:24.832000,1554.791,2.0,0.0,2.25,2021-01-19,1.500,2021-01-19,3.15,5.95
35,7,5fd41bf508717e1833d8aed7,1994.0,Mexico,NaN,NaN,Mexico,Male,APPROVED,2021-01-18 10:57:15.631000,...,2021-01-18 09:04:21.665000,2039.578,4.0,30.0,2.25,2021-01-18,3.000,2021-02-17,3.15,8.75
36,70,5d430fdf871f1700017b2a81,NaN,Spain,Spain,Catalan,Spain,Male,APPROVED,2021-01-19 10:41:24.134000,...,2021-01-19 10:41:23.434000,5480.347,5.0,7.0,2.25,2021-01-19,3.750,2021-01-26,3.15,10.15
37,74,5aa7b522b5e2110001c74775,1983.0,United Kingdom,United Kingdom,English,United Kingdom,Female,APPROVED,2021-01-19 10:41:07.404000,...,2021-01-19 09:29:45.407000,1165.564,5.0,30.0,2.25,2021-01-19,3.750,2021-02-18,3.15,10.15
38,75,5d00bb3b51669b000136a986,1982.0,Poland,Poland,Polish,Poland,Male,APPROVED,2021-01-19 11:50:31.960000,...,2021-01-19 09:56:27.049000,2749.949,5.0,30.0,2.25,2021-01-19,3.750,2021-02-18,3.15,10.15
39,80,5fa69c24315bfb2d0a37c685,2000.0,Poland,Poland,DATA EXPIRED,Poland,Male,APPROVED,2021-01-19 11:00:49.360000,...,2021-01-19 09:44:37.014000,2124.200,4.0,7.0,2.25,2021-01-19,3.000,2021-01-26,3.15,8.75
40,81,5c6cb4163023800001e71898,1994.0,Greece,Greece,Greek,Greece,Male,APPROVED,2021-01-19 10:59:36.907000,...,2021-01-19 09:44:01.279000,1939.612,3.5,0.0,2.25,2021-01-19,2.625,2021-01-19,3.15,8.05
41,85,5e2db0f07dc16b3a611516bd,1982.0,United Kingdom,United Kingdom,English,United Kingdom,Female,APPROVED,2021-01-19 11:00:04.816000,...,2021-01-19 09:32:30.113000,1199.651,4.5,1.0,2.25,2021-01-19,3.375,2021-01-20,3.15,9.45
42,9,5fea6632bf9ae4a79153efdf,1976.0,Serbia,Austria,DATA EXPIRED,Serbia,Male,APPROVED,2021-01-18 10:31:49.885000,...,2021-01-18 09:14:43.719000,2630.121,5.0,1.0,2.25,2021-01-18,3.750,2021-01-19,3.15,10.15
43,90,5cf67b30c5cf0e00010c00fc,1982.0,Spain,Spain,Spanish,Spain,Female,APPROVED,2021-01-19 11:50:23.483000,...,2021-01-19 09:38:40.135000,1760.117,3.0,0.0,2.25,2021-01-19,2.250,2021-01-19,3.15,7.35
44,91,5f256074297aac1d8ef7382d,1997.0,Hungary,Hungary,Hungarian,Hungary,Male,APPROVED,2021-01-19 11:00:20.935000,...,2021-01-19 09:41:29.860000,1761.560,2.5,0.0,2.25,2021-01-19,1.875,2021-01-19,3.15,6.65
45,92,5f91b067130f8504520cdd6f,1995.0,Italy,United Kingdom,DATA EXPIRED,Italy,Male,APPROVED,2021-01-19 11:00:37.754000,...,2021-01-19 09:40:37.424000,1610.890,4.5,15.0,2.25,2021-01-19,3.375,2021-02-03,3.15,9.45
46,93,5f4756db83588013e9e31bfc,1990.0,South Africa,South Africa,DATA EXPIRED,South Africa,Male,APPROVED,2021-01-19 11:00:24.989000,...,2021-01-19 09:47:57.111000,1964.713,2.0,0.0,2.25,2021-01-19,1.500,2021-01-19,3.15,5.95
47,94,5ecfc227f036c902457fc44c,1998.0,United Kingdom,NaN,NaN,United Kingdom,Female,APPROVED,2021-01-19 11:00:12.689000,...,2021-01-19 09:42:59.122000,2020.693,4.0,15.0,2.25,2021-01-19,3.000,2021-02-03,3.15,8.75
48,96,5eb9940830ab6c098bd1943d,1997.0,Israel,Israel,Hebrew,Israel,Male,APPROVED,2021-01-19 11:00:08.479000,...,2021-01-19 09:38:16.326000,1679.141,4.5,90.0,2.25,2021-01-19,3.375,2021-04-19,3.15,9.45
49,97,5f68fe5be5cc370c0a0911de,1988.0,United Kingdom,United Kingdom,DATA EXPIRED,United Kingdom,Female,APPROVED,2021-01-19 11:00:34.269000,...,2021-01-19 09:57:42.785000,2384.451,4.5,30.0,2.25,2021-01-19,3.375,2021-02-18,3.15,9.45
50,98,5f779405dacc842fc44bc767,1996.0,Portugal,Portugal,DATA EXPIRED,Portugal,Male,APPROVED,2021-01-19 11:50:19.976000,...,2021-01-19 09:48:30.781000,1782.482,4.0,30.0,2.25,2021-01-19,3.000,2021-02-18,3.15,8.75

# Export modified prolific data

In [19]:
data_pay.to_csv('C:/Users/User/Google Drive/Masterarbeit/Acquise/data_pay.csv', index=False, header=True)