In [1]:
import datetime
import matplotlib.pyplot as plt
import numpy as np
import os
import pandas as pd
import random
import sys
from datetime import timedelta  

if sys.version_info[0] < 3: 
    from StringIO import StringIO
else:
    from io import StringIO
    
from IPython.display import HTML
def View(df):
    css = """<style>
    table { border-collapse: collapse; border: 3px solid #eee; }
    table tr th:first-child { background-color: #eeeeee; color: #333; font-weight: bold }
    table thead th { background-color: #eee; color: #000; }
    tr, th, td { border: 1px solid #ccc; border-width: 1px 0 0 1px; border-collapse: collapse;
    padding: 3px; font-family: monospace; font-size: 10px }</style>
    """
    s  = '<script type="text/Javascript">'
    s += 'var win = window.open("", "Title", "toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=yes, resizable=yes, width=780, height=200, top="+(screen.height-400)+", left="+(screen.width-840));'
    s += 'win.document.body.innerHTML = \'' + (df.to_html() + css).replace("\n",'\\') + '\';'
    s += '</script>'
    return(HTML(s+css))    
    
print("Current Working directory " , os.getcwd())

Current Working directory  C:\Users\User\GitHub\WebET_Analysis

In [2]:
data_et = pd.read_csv(r'C:/Users/User/GitHub/WebET_Analysis/data_jupyter/data_et.csv')
data_et_fix = pd.read_csv(r'C:/Users/User/GitHub/WebET_Analysis/data_jupyter/data_et_fix.csv')
data_et_choice = pd.read_csv(r'C:/Users/User/GitHub/WebET_Analysis/data_jupyter/data_et_choice.csv')

data_trial = pd.read_csv(r'C:/Users/User/GitHub/WebET_Analysis/data_jupyter/data_trial.csv')
data_trial_fix = pd.read_csv(r'C:/Users/User/GitHub/WebET_Analysis/data_jupyter/data_trial_fix.csv')
data_trial_choice = pd.read_csv(r'C:/Users/User/GitHub/WebET_Analysis/data_jupyter/data_trial_choice.csv')

data_subject = pd.read_csv(r'C:/Users/User/GitHub/WebET_Analysis/data_jupyter/data_subject.csv') \
    .rename(columns=
            {
                'chosenAmount': 'bonus_pay',
                'chosenDelay': 'bonus_delay'
            }
           )    

overview = pd.DataFrame(
    [
        [len(data_et)],
        [len(data_et_fix)],
        [len(data_et_choice)],
        [len(data_trial)],
        [len(data_trial_fix)],
        [len(data_trial_choice)],
        [len(data_subject)]
    ], 
    columns=['length'],
    index=['data_et', 'data_et_fix', 'data_et_choice', 
           'data_trial', 'data_trial_fix', 'data_trial_choice', 
           'data_subject'])
print(overview)

                   length
data_et            618566
data_et_fix         57762
data_et_choice     143127
data_trial          30362
data_trial_fix        918
data_trial_choice    3655
data_subject           73

# Approve subjects

In [3]:
if 'trial_length' in data_subject.columns: 
    print('trial_length already added!')
else:
    output = []
    for subject in data_trial['run_id'].unique():
        prolificID = data_trial.loc[data_trial['run_id']==subject, 'prolificID'].unique()[0]
        trial_length = len(data_trial.loc[data_trial['run_id']==subject, 'trial_index'].unique())
        output.append([subject, prolificID, trial_length])
    output = pd.DataFrame(output,
                 columns=['run_id', 'prolificID', 'trial_length']
                )

    data_subject = data_subject.merge(output, on=['run_id', 'prolificID'], how='left')

In [4]:
data_et = data_et.merge(
    data_trial.loc[:, ['run_id', 'chinFirst', 'trial_index', 'trial_type', 'task_nr']], 
    on=['run_id', 'trial_index'], 
    how='left'
)

In [5]:
output = []
for subject in data_et['run_id'].unique():
    m_x_fix = data_et.loc[
        (data_et['run_id']==subject) &
        (data_et['trial_type']=='eyetracking-fix-object') &
        ~((data_et['chinFirst']==1) & (data_et['task_nr']==2) |
          (data_et['chinFirst']==0) & (data_et['task_nr']==3) 
         ), 
        'x'
    ].mean()
    m_x_choice = data_et.loc[
        (data_et['run_id']==subject) &
        (data_et['trial_type']=='eyetracking-choice'), 
        'x'
    ].mean()

    m_y_fix = data_et.loc[
        (data_et['run_id']==subject) &
        (data_et['trial_type']=='eyetracking-fix-object') &
        ~((data_et['chinFirst']==1) & (data_et['task_nr']==2) |
          (data_et['chinFirst']==0) & (data_et['task_nr']==3) 
         ), 
        'y'
    ].mean()
    m_y_choice = data_et.loc[
        (data_et['run_id']==subject) &
        (data_et['trial_type']=='eyetracking-choice'), 
        'y'
    ].mean()

    m_count_fix = data_et.loc[
        (data_et['run_id']==subject) &
        (data_et['trial_type']=='eyetracking-fix-object') &
        ~((data_et['chinFirst']==1) & (data_et['task_nr']==2) |
          (data_et['chinFirst']==0) & (data_et['task_nr']==3) 
         ), 
        'x'
    ].count()

    m_count_choice = data_et.loc[
        (data_et['run_id']==subject) &
        (data_et['trial_type']=='eyetracking-choice'), 
        'x'
    ].count()
    
    m_choseTop = data_trial_choice.loc[data_trial_choice['run_id']==subject,
                                       'choseTop'].mean()

    output.append([subject, m_x_fix, m_y_fix, m_x_choice, m_y_choice, 
                   m_count_fix, m_count_choice, 
                   m_choseTop])

output = pd.DataFrame(output, 
                      columns=['run_id', 'm_x_fix', 'm_y_fix', 'm_x_choice', 'm_y_choice', 
                               'm_count_fix', 'm_count_choice',
                               'm_choseTop'])
output

data_subject = data_subject.merge(output, on='run_id', how='left')

## These subjects await review

In [6]:
data_subject.loc[data_subject['status']=='AWAITING REVIEW', 
                 ['run_id', 'prolificID', 'trial_length',
                 'm_x_fix', 'm_y_fix', 'm_x_choice', 'm_y_choice', 'm_count_fix', 'm_count_choice',
                 'm_choseTop']
                ].sort_values(by='prolificID')

Empty DataFrame
Columns: [run_id, prolificID, trial_length, m_x_fix, m_y_fix, m_x_choice, m_y_choice, m_count_fix, m_count_choice, m_choseTop]
Index: []

In [7]:
if 'choice_rt' in data_subject.columns:
    print('choice_rt already added!')
else: 
    grouped = data_trial.loc[data_trial['trial_type']=='eyetracking-choice', :] \
        .groupby(['prolificID'])['trial_duration_exact'].mean() \
        .reset_index() \
        .rename(columns={'trial_duration_exact': 'choice_rt'})
    data_subject = data_subject.merge(grouped, on='prolificID', how='left')

data_subject.loc[
    data_subject['status']=='AWAITING REVIEW', 
    ['run_id', 'prolificID', 'webcam_fps', 'choice_rt', 'bonus_pay', 'bonus_delay']
] \
    .sort_values(by='run_id')

choice_rt already added!

Empty DataFrame
Columns: [run_id, prolificID, webcam_fps, choice_rt, bonus_pay, bonus_delay]
Index: []

# Basic payment

In [14]:
data_pay = data_subject.loc[data_subject['status']=='APPROVED', 
                            [
                                'run_id', 'prolificID', 
                                'age',  'Country of Birth', 'Current Country of Residence', 'First Language',
                                'Nationality', 'Sex',
                                'status', 'reviewed_at_datetime', 'Country of Birth', 'entered_code',
                                'session_id', 'started_datetime', 'completed_date_time', 'time_taken',
                                'bonus_pay', 'bonus_delay'
                            ]
                           ]

data_pay['basic_pay'] = 2.25
data_pay.loc[:, ['bonus_pay', 'bonus_delay']].head(5)

  bonus_pay bonus_delay
1      $4.5    180 days
4      $3.5       Today
6      $4.5     90 days
7      $4.5      7 days
8        $5     30 days

# Bonus payment

Reformat payments

In [16]:
data_pay['bonus_delay'] = data_pay['bonus_delay'].astype(str)
data_pay['bonus_delay'] = data_pay['bonus_delay'] \
    .replace(['Today', 'Tomorrow', '7 days', 
          '15 days', '30 days', '90 days', 
          '180 days'], 
         [0, 1, 7, 15, 30, 90, 180]) \
    .astype(float)

data_pay['bonus_pay'] = data_pay['bonus_pay'].astype(str)
data_pay['bonus_pay'] = data_pay['bonus_pay'] \
    .replace({'\$':''}, regex = True) \
    .replace('50 cent', 0.5) \
    .astype(float)

data_pay.loc[:, ['bonus_pay', 'bonus_delay']].head(5)

   bonus_pay  bonus_delay
1        4.5        180.0
4        3.5          0.0
6        4.5         90.0
7        4.5          7.0
8        5.0         30.0

## Replace empty values with the best bonus reward

In [17]:
# For two subjects, the bonus payment was not recorded
data_pay.loc[
    data_pay['prolificID'].isin(
        ['5fea6632bf9ae4a79153efdf', 
         '5b8969006651ea000118e42e', 
         '5fb2af792942a58ffe303948', 
        ]
    ), ['bonus_pay', 'bonus_delay']] = [5, 1]

data_pay.loc[data_pay[['bonus_pay', 'bonus_delay']].isnull().any(axis=1), :]

Empty DataFrame
Columns: [run_id, prolificID, age, Country of Birth, Current Country of Residence, First Language, Nationality, Sex, status, reviewed_at_datetime, Country of Birth, entered_code, session_id, started_datetime, completed_date_time, time_taken, bonus_pay, bonus_delay, basic_pay]
Index: []

## What bonus is due today?

In [18]:
def add_recorded_date(data, data_trial):
    output = []

    for subject in data_trial['run_id'].unique():
        thisSubject = data_trial.loc[data_trial['run_id']==subject] \
            .reset_index(drop=True)
        date_time_obj = datetime.datetime.strptime(
            thisSubject.loc[0, 'recorded_at'], '%Y-%m-%d %H:%M:%S')

        output.append([thisSubject.loc[0, 'run_id'], date_time_obj.date()])
        
    output = pd.DataFrame(output, columns=['run_id', 'date']) 
    
    if 'date' in data.columns: data = data.drop(columns=['date'])
    data = data.merge(output, on='run_id', how='left')
    return data

data_pay = add_recorded_date(data_pay, data_trial)
    
data_pay['completed_date']=data_pay.apply(
    lambda x: datetime.datetime.strptime(
        x['completed_date_time'], '%Y-%m-%d %H:%M:%S.%f') \
            .date(),
    axis=1)
data_pay['bonus_pay'].unique()

array([4.5, 3.5, 5. , 4. , 3. , 2.5, 0.5, 2. ])

In [19]:
data_pay['reward_pound'] = data_pay['bonus_pay'] * 0.75

In [20]:
data_pay['due_on'] = data_pay['completed_date'] +  data_pay['bonus_delay'].map(datetime.timedelta) 

data_pay.loc[:, 
               [
                   'prolificID', 'run_id',
                   'Nationality', 'Sex',  
                   'completed_date', 'bonus_pay', 'bonus_delay', 
                   'reward_pound'
               ]
              ]. sort_values(by='completed_date')

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\arrays\datetimelike.py:1342: PerformanceWarning: Adding/subtracting object-dtype array to TimedeltaArray not vectorized
  warnings.warn(

,prolificID,run_id,Nationality,Sex,completed_date,bonus_pay,bonus_delay,reward_pound
14,5f0cb319d29147695796a208,37,Italy,Male,2021-01-18,3.0,0.0,2.250
26,5f4e08aafb74230a29cb4ef0,6,Poland,Male,2021-01-18,5.0,15.0,3.750
22,5ea3f75481a44e39aa318256,5,Israel,Male,2021-01-18,4.5,30.0,3.375
19,5f946436ae32a127565d9405,43,Portugal,Male,2021-01-18,4.0,30.0,3.000
18,5fcbb3066829ff1a601fe080,42,United Kingdom,Female,2021-01-18,5.0,1.0,3.750
17,5f881c7d29650a26096e77a3,41,United Kingdom,Male,2021-01-18,4.5,30.0,3.375
16,5f96fc2552ce3f040af63bbc,4,Spain,Male,2021-01-18,4.5,30.0,3.375
15,5f1e9db721e4f101783fe21c,38,Poland,Male,2021-01-18,4.0,1.0,3.000
13,5f8472685956c40c720d0936,36,Italy,Male,2021-01-18,0.5,0.0,0.375
12,5ea94df3a879f002f3e9a812,32,Poland,Female,2021-01-18,4.5,90.0,3.375
11,5eeaa0ffaa6af11cf32ce057,30,Poland,Male,2021-01-18,3.0,0.0,2.250
30,5fd41bf508717e1833d8aed7,7,Mexico,Male,2021-01-18,4.0,30.0,3.000
9,5cf0ccf488abf10019fb775d,25,United Kingdom,Female,2021-01-18,4.5,90.0,3.375
8,5f77a902fc647a327b77004a,24,United Kingdom,Female,2021-01-18,3.0,0.0,2.250
7,5f860a189bc695131f22ec9c,19,Poland,Male,2021-01-18,4.5,7.0,3.375
1,5c5684ef9d244c0001b29f1e,11,United States,Male,2021-01-18,3.5,0.0,2.625
4,5b4e65de09f5af0001080f45,13,Poland,Male,2021-01-18,5.0,30.0,3.750
10,5f561a95aa1c4ea13672f138,28,Italy,Male,2021-01-18,2.5,0.0,1.875
32,5d00bb3b51669b000136a986,75,Poland,Male,2021-01-19,5.0,30.0,3.750
33,5fa69c24315bfb2d0a37c685,80,Poland,Male,2021-01-19,4.0,7.0,3.000
34,5c6cb4163023800001e71898,81,Greece,Male,2021-01-19,3.5,0.0,2.625
35,5e2db0f07dc16b3a611516bd,85,United Kingdom,Female,2021-01-19,4.5,1.0,3.375
37,5f256074297aac1d8ef7382d,91,Hungary,Male,2021-01-19,2.5,0.0,1.875
36,5cf67b30c5cf0e00010c00fc,90,Spain,Female,2021-01-19,3.0,0.0,2.250
40,5ecfc227f036c902457fc44c,94,United Kingdom,Female,2021-01-19,4.0,15.0,3.000
39,5f4756db83588013e9e31bfc,93,South Africa,Male,2021-01-19,2.0,0.0,1.500
38,5f91b067130f8504520cdd6f,92,Italy,Male,2021-01-19,4.5,15.0,3.375
31,5aa7b522b5e2110001c74775,74,United Kingdom,Female,2021-01-19,5.0,30.0,3.750
41,5eb9940830ab6c098bd1943d,96,Israel,Male,2021-01-19,4.5,90.0,3.375
0,600063f2943eab0acc812ed8,103,Italy,Male,2021-01-19,4.5,180.0,3.375
21,5f5793d85411a8251740e602,47,Poland,Male,2021-01-19,4.5,0.0,3.375
28,5bd170999afb5b00015ba3b1,66,Portugal,Female,2021-01-19,5.0,30.0,3.750
27,5fc6bcbc6da34d0f8dd78a3a,63,Poland,Male,2021-01-19,4.0,15.0,3.000
25,5fe6fb05b9b609059e4613e0,59,Mexico,Male,2021-01-19,4.0,15.0,3.000
24,5de5157820c5aa09b7a53b89,58,Greece,Male,2021-01-19,5.0,15.0,3.750
23,5e79d99f6873570009367716,56,United Kingdom,Female,2021-01-19,4.5,0.0,3.375
42,5f68fe5be5cc370c0a0911de,97,United Kingdom,Female,2021-01-19,4.5,30.0,3.375
20,5f1aac6058391f01dacbf619,45,Poland,Male,2021-01-19,4.5,30.0,3.375
6,5e53a7b4d9a7ea3a2b062da0,131,United Kingdom,Female,2021-01-19,3.5,0.0,2.625
5,5fea19869bf07d97b4a87ae8,130,Spain,Male,2021-01-19,4.0,0.0,3.000
3,5f01a0893963d02ea1d65d12,128,Greece,Male,2021-01-19,4.5,7.0,3.375
2,5c0e4e3d87e876000151cfec,126,Poland,Female,2021-01-19,4.5,90.0,3.375
29,5cfb9f6f288ca80001169952,67,Poland,Male,2021-01-19,2.0,0.0,1.500
43,5f779405dacc842fc44bc767,98,Portugal,Male,2021-01-19,4.0,30.0,3.000

In [21]:
bonus_due_today = data_pay.loc[data_pay['due_on']==datetime.datetime.now().date(), :]
bonus_due_today['reward_pound'] = bonus_due_today['reward_pound'].round(2)
bonus_due_today

Empty DataFrame
Columns: [run_id, prolificID, age, Country of Birth, Current Country of Residence, First Language, Nationality, Sex, status, reviewed_at_datetime, Country of Birth, entered_code, session_id, started_datetime, completed_date_time, time_taken, bonus_pay, bonus_delay, basic_pay, date, completed_date, reward_pound, due_on]
Index: []

[0 rows x 23 columns]

In [22]:
bonus_due_today.loc[: , ['prolificID', 'reward_pound']] \
    .to_csv('C:/Users/User/Google Drive/Masterarbeit/Acquise/bonusToday.csv', 
            index=False, 
            header=False
           )
print(bonus_due_today['due_on'].unique())

[]

# Total costs

In [23]:
data_pay['basic_cost'] = data_pay['basic_pay'] * 1.4
data_pay['total_cost'] = (data_pay['basic_pay'] + data_pay['bonus_pay']) * 1.4
print('Basic Costs: ' + str(sum(data_pay['basic_cost'])))
print('Total Costs: ' + str(sum(data_pay['total_cost'])))
data_pay

Basic Costs: 138.6000000000001
Total Costs: 383.59999999999985

,run_id,prolificID,age,Country of Birth,Current Country of Residence,First Language,Nationality,Sex,status,reviewed_at_datetime,...,time_taken,bonus_pay,bonus_delay,basic_pay,date,completed_date,reward_pound,due_on,basic_cost,total_cost
0,103,600063f2943eab0acc812ed8,19.0,Italy,Italy,NaN,Italy,Male,APPROVED,2021-01-19 10:58:01.081000,...,1760.968,4.5,180.0,2.25,2021-01-19,2021-01-19,3.375,2021-07-18,3.15,9.45
1,11,5c5684ef9d244c0001b29f1e,29.0,Hong Kong,United States,Chinese,United States,Male,APPROVED,2021-01-18 10:53:28.738000,...,1227.532,3.5,0.0,2.25,2021-01-18,2021-01-18,2.625,2021-01-18,3.15,8.05
2,126,5c0e4e3d87e876000151cfec,29.0,Poland,Poland,Polish,Poland,Female,APPROVED,2021-01-19 12:36:10.712000,...,1912.745,4.5,90.0,2.25,2021-01-19,2021-01-19,3.375,2021-04-19,3.15,9.45
3,128,5f01a0893963d02ea1d65d12,26.0,Germany,Greece,Greek,Greece,Male,APPROVED,2021-01-19 12:36:47.163000,...,2288.987,4.5,7.0,2.25,2021-01-19,2021-01-19,3.375,2021-01-26,3.15,9.45
4,13,5b4e65de09f5af0001080f45,29.0,Poland,Poland,Polish,Poland,Male,APPROVED,2021-01-18 10:56:07.011000,...,1692.194,5.0,30.0,2.25,2021-01-18,2021-01-18,3.750,2021-02-17,3.15,10.15
5,130,5fea19869bf07d97b4a87ae8,19.0,Spain,Spain,NaN,Spain,Male,APPROVED,2021-01-19 13:24:23.588000,...,1349.099,4.0,0.0,2.25,2021-01-19,2021-01-19,3.000,2021-01-19,3.15,8.75
6,131,5e53a7b4d9a7ea3a2b062da0,40.0,United Kingdom,United Kingdom,English,United Kingdom,Female,APPROVED,2021-01-19 13:24:22.246000,...,1415.591,3.5,0.0,2.25,2021-01-19,2021-01-19,2.625,2021-01-19,3.15,8.05
7,19,5f860a189bc695131f22ec9c,20.0,Poland,Poland,DATA EXPIRED,Poland,Male,APPROVED,2021-01-18 10:57:59.489000,...,2116.522,4.5,7.0,2.25,2021-01-18,2021-01-18,3.375,2021-01-25,3.15,9.45
8,24,5f77a902fc647a327b77004a,27.0,United Kingdom,United Kingdom,DATA EXPIRED,United Kingdom,Female,APPROVED,2021-01-18 17:54:59.440000,...,2115.673,3.0,0.0,2.25,2021-01-18,2021-01-18,2.250,2021-01-18,3.15,7.35
9,25,5cf0ccf488abf10019fb775d,18.0,New Zealand,United Kingdom,Twi,United Kingdom,Female,APPROVED,2021-01-18 17:55:09.667000,...,1913.891,4.5,90.0,2.25,2021-01-18,2021-01-18,3.375,2021-04-18,3.15,9.45
10,28,5f561a95aa1c4ea13672f138,37.0,Italy,United Kingdom,DATA EXPIRED,Italy,Male,APPROVED,2021-01-18 17:55:18.379000,...,1197.589,2.5,0.0,2.25,2021-01-18,2021-01-18,1.875,2021-01-18,3.15,6.65
11,30,5eeaa0ffaa6af11cf32ce057,20.0,Poland,Poland,Polish,Poland,Male,APPROVED,2021-01-18 17:55:26.984000,...,1351.104,3.0,0.0,2.25,2021-01-18,2021-01-18,2.250,2021-01-18,3.15,7.35
12,32,5ea94df3a879f002f3e9a812,23.0,Poland,Poland,Polish,Poland,Female,APPROVED,2021-01-18 17:55:32.282000,...,4402.360,4.5,90.0,2.25,2021-01-18,2021-01-18,3.375,2021-04-18,3.15,9.45
13,36,5f8472685956c40c720d0936,21.0,Italy,Italy,DATA EXPIRED,Italy,Male,APPROVED,2021-01-18 17:55:37.264000,...,1453.841,0.5,0.0,2.25,2021-01-18,2021-01-18,0.375,2021-01-18,3.15,3.85
14,37,5f0cb319d29147695796a208,36.0,Italy,United Kingdom,Italian,Italy,Male,APPROVED,2021-01-18 17:55:43.824000,...,1531.289,3.0,0.0,2.25,2021-01-18,2021-01-18,2.250,2021-01-18,3.15,7.35
15,38,5f1e9db721e4f101783fe21c,19.0,Poland,Poland,Polish,Poland,Male,APPROVED,2021-01-19 11:09:24.649000,...,3482.451,4.0,1.0,2.25,2021-01-18,2021-01-18,3.000,2021-01-19,3.15,8.75
16,4,5f96fc2552ce3f040af63bbc,23.0,Spain,Spain,DATA EXPIRED,Spain,Male,APPROVED,2021-01-18 10:57:45.132000,...,1886.868,4.5,30.0,2.25,2021-01-18,2021-01-18,3.375,2021-02-17,3.15,9.45
17,41,5f881c7d29650a26096e77a3,28.0,United Kingdom,United Kingdom,DATA EXPIRED,United Kingdom,Male,APPROVED,2021-01-18 17:55:48.738000,...,1310.641,4.5,30.0,2.25,2021-01-18,2021-01-18,3.375,2021-02-17,3.15,9.45
18,42,5fcbb3066829ff1a601fe080,34.0,United Kingdom,United Kingdom,DATA EXPIRED,United Kingdom,Female,APPROVED,2021-01-18 17:55:53.348000,...,1506.437,5.0,1.0,2.25,2021-01-18,2021-01-18,3.750,2021-01-19,3.15,10.15
19,43,5f946436ae32a127565d9405,24.0,Portugal,Portugal,NaN,Portugal,Male,APPROVED,2021-01-18 17:55:58.249000,...,1667.728,4.0,30.0,2.25,2021-01-18,2021-01-18,3.000,2021-02-17,3.15,8.75
20,45,5f1aac6058391f01dacbf619,32.0,Poland,Poland,Polish,Poland,Male,APPROVED,2021-01-19 11:00:16.312000,...,1609.939,4.5,30.0,2.25,2021-01-19,2021-01-19,3.375,2021-02-18,3.15,9.45
21,47,5f5793d85411a8251740e602,19.0,Poland,Poland,DATA EXPIRED,Poland,Male,APPROVED,2021-01-19 11:00:28.992000,...,1557.240,4.5,0.0,2.25,2021-01-19,2021-01-19,3.375,2021-01-19,3.15,9.45
22,5,5ea3f75481a44e39aa318256,26.0,Israel,Israel,Russian,Israel,Male,APPROVED,2021-01-18 10:57:35.455000,...,1536.061,4.5,30.0,2.25,2021-01-18,2021-01-18,3.375,2021-02-17,3.15,9.45
23,56,5e79d99f6873570009367716,26.0,United Kingdom,United Kingdom,English,United Kingdom,Female,APPROVED,2021-01-19 11:50:27.571000,...,1159.061,4.5,0.0,2.25,2021-01-19,2021-01-19,3.375,2021-01-19,3.15,9.45
24,58,5de5157820c5aa09b7a53b89,21.0,Greece,Greece,Greek,Greece,Male,APPROVED,2021-01-19 10:59:59.217000,...,1702.131,5.0,15.0,2.25,2021-01-19,2021-01-19,3.750,2021-02-03,3.15,10.15
25,59,5fe6fb05b9b609059e4613e0,23.0,Mexico,Mexico,DATA EXPIRED,Mexico,Male,APPROVED,2021-01-19 11:01:03.595000,...,1938.240,4.0,15.0,2.25,2021-01-19,2021-01-19,3.000,2021-02-03,3.15,8.75
26,6,5f4e08aafb74230a29cb4ef0,19.0,Poland,Poland,DATA EXPIRED,Poland,Male,APPROVED,2021-01-18 10:58:32.736000,...,1589.581,5.0,15.0,2.25,2021-01-18,2021-01-18,3.750,2021-02-02,3.15,10.15
27,63,5fc6bcbc6da34d0f8dd78a3a,18.0,Poland,Poland,DATA EXPIRED,Poland,Male,APPROVED,2021-01-19 11:00:59.173000,...,3026.498,4.0,15.0,2.25,2021-01-19,2021-01-19,3.000,2021-02-03,3.15,8.75
28,66,5bd170999afb5b00015ba3b1,51.0,Portugal,Portugal,Portuguese,Portugal,Female,APPROVED,2021-01-19 10:59:31.598000,...,1921.967,5.0,30.0,2.25,2021-01-19,2021-01-19,3.750,2021-02-18,3.15,10.15
29,67,5cfb9f6f288ca80001169952,30.0,Poland,Poland,Polish,Poland,Male,APPROVED,2021-01-19 10:59:40.829000,...,1554.791,2.0,0.0,2.25,2021-01-19,2021-01-19,1.500,2021-01-19,3.15,5.95
30,7,5fd41bf508717e1833d8aed7,26.0,Mexico,NaN,NaN,Mexico,Male,APPROVED,2021-01-18 10:57:15.631000,...,2039.578,4.0,30.0,2.25,2021-01-18,2021-01-18,3.000,2021-02-17,3.15,8.75
31,74,5aa7b522b5e2110001c74775,37.0,United Kingdom,United Kingdom,English,United Kingdom,Female,APPROVED,2021-01-19 10:41:07.404000,...,1165.564,5.0,30.0,2.25,2021-01-19,2021-01-19,3.750,2021-02-18,3.15,10.15
32,75,5d00bb3b51669b000136a986,38.0,Poland,Poland,Polish,Poland,Male,APPROVED,2021-01-19 11:50:31.960000,...,2749.949,5.0,30.0,2.25,2021-01-19,2021-01-19,3.750,2021-02-18,3.15,10.15
33,80,5fa69c24315bfb2d0a37c685,20.0,Poland,Poland,DATA EXPIRED,Poland,Male,APPROVED,2021-01-19 11:00:49.360000,...,2124.200,4.0,7.0,2.25,2021-01-19,2021-01-19,3.000,2021-01-26,3.15,8.75
34,81,5c6cb4163023800001e71898,26.0,Greece,Greece,Greek,Greece,Male,APPROVED,2021-01-19 10:59:36.907000,...,1939.612,3.5,0.0,2.25,2021-01-19,2021-01-19,2.625,2021-01-19,3.15,8.05
35,85,5e2db0f07dc16b3a611516bd,38.0,United Kingdom,United Kingdom,English,United Kingdom,Female,APPROVED,2021-01-19 11:00:04.816000,...,1199.651,4.5,1.0,2.25,2021-01-19,2021-01-19,3.375,2021-01-20,3.15,9.45
36,90,5cf67b30c5cf0e00010c00fc,38.0,Spain,Spain,Spanish,Spain,Female,APPROVED,2021-01-19 11:50:23.483000,...,1760.117,3.0,0.0,2.25,2021-01-19,2021-01-19,2.250,2021-01-19,3.15,7.35
37,91,5f256074297aac1d8ef7382d,23.0,Hungary,Hungary,Hungarian,Hungary,Male,APPROVED,2021-01-19 11:00:20.935000,...,1761.560,2.5,0.0,2.25,2021-01-19,2021-01-19,1.875,2021-01-19,3.15,6.65
38,92,5f91b067130f8504520cdd6f,25.0,Italy,United Kingdom,DATA EXPIRED,Italy,Male,APPROVED,2021-01-19 11:00:37.754000,...,1610.890,4.5,15.0,2.25,2021-01-19,2021-01-19,3.375,2021-02-03,3.15,9.45
39,93,5f4756db83588013e9e31bfc,30.0,South Africa,South Africa,DATA EXPIRED,South Africa,Male,APPROVED,2021-01-19 11:00:24.989000,...,1964.713,2.0,0.0,2.25,2021-01-19,2021-01-19,1.500,2021-01-19,3.15,5.95
40,94,5ecfc227f036c902457fc44c,22.0,United Kingdom,NaN,NaN,United Kingdom,Female,APPROVED,2021-01-19 11:00:12.689000,...,2020.693,4.0,15.0,2.25,2021-01-19,2021-01-19,3.000,2021-02-03,3.15,8.75
41,96,5eb9940830ab6c098bd1943d,25.0,Israel,Israel,Hebrew,Israel,Male,APPROVED,2021-01-19 11:00:08.479000,...,1679.141,4.5,90.0,2.25,2021-01-19,2021-01-19,3.375,2021-04-19,3.15,9.45
42,97,5f68fe5be5cc370c0a0911de,32.0,United Kingdom,United Kingdom,DATA EXPIRED,United Kingdom,Female,APPROVED,2021-01-19 11:00:34.269000,...,2384.451,4.5,30.0,2.25,2021-01-19,2021-01-19,3.375,2021-02-18,3.15,9.45
43,98,5f779405dacc842fc44bc767,24.0,Portugal,Portugal,DATA EXPIRED,Portugal,Male,APPROVED,2021-01-19 11:50:19.976000,...,1782.482,4.0,30.0,2.25,2021-01-19,2021-01-19,3.000,2021-02-18,3.15,8.75

# Export modified prolific data

In [24]:
data_pay.to_csv('C:/Users/User/Google Drive/Masterarbeit/Acquise/data_pay.csv', index=False, header=True)

# Feedback

In [25]:
print('Success! Script ran through.')

Success! Script ran through.